In [87]:
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier

In [88]:
iris=datasets.load_iris()

In [89]:
x_all=iris.data
y_all=iris.target
print(np.hstack([x_all,y_all.reshape((-1,1))]))

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

## train_test_split

In [90]:
# 随机索引
shuffle_indexes = np.random.permutation(len(x_all))
shuffle_indexes

array([118, 100,  10,  97,  70,   7, 123, 146,  71,  18,  43,  14,  31,
        60, 105, 129,  22,  23,  26,   5,  11, 114,  38,  17, 133,  20,
       136,  73, 121, 117,  27, 144, 120,  79,  90,  67,  12,  98,  51,
        87, 122,  34, 135,   4,   2, 134,  85,  61, 147,  81, 103, 131,
         6,  72,  39,  19,  59,  47,   9,  58, 138,   0,  37,  66, 128,
       102,  69,  76,  82,  75,  63,  13,   8,  29,  48,  46,  54, 113,
        78,  56, 142,  95,  84,  57,  88,  74,   1,  41, 127, 101, 125,
        55, 126, 137,  50,  77, 141,  42,  68,  83,  92,  35, 130,  28,
        15, 143, 115, 107,  62,  16,  45, 148, 132,  80,  91, 108, 119,
       106,  93,  33,  99,  94, 104,  32, 110,  64,  49,  21, 124, 112,
        65,  89, 111,  36,  52, 140,  86,  25,  40,  44,  96,  53,  24,
       109, 149, 116, 139,   3,  30, 145])

In [91]:
test_ratio = 0.2
test_size = int(len(shuffle_indexes)*test_ratio)
print("测试集大小：",test_size)

测试集大小： 30


In [92]:
test_index=shuffle_indexes[:test_size:]
train_index=shuffle_indexes[test_size:]

In [93]:
x_train=x_all[train_index]
y_train=y_all[train_index]

x_test=x_all[test_index]
y_test=y_all[test_index]

In [94]:
KNN_classifier=KNeighborsClassifier(n_neighbors=6)

In [95]:
KNN_classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [96]:
y_predict=KNN_classifier.predict(x_test)

In [97]:
y_predict

array([2, 2, 0, 1, 2, 0, 2, 2, 1, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 2,
       0, 0, 1, 0, 2, 1, 2, 2])

In [98]:
y_predict==y_test

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True])

In [99]:
np.all(y_predict==y_test)

False