### 多元线性回归

需要拟合的目标方程：$ y=w_{1}x_{1}+w_{2}x_{2}+\ldots +w_{n}x_{n}+b $

<br/>

则对于我们每一个有n纬特征的特征向量 $(x^{\left( i\right) }_{1},x^{\left( i\right) }_{2},x^{\left( i\right) }_{3},\ldots ,x^{\left( i\right) }_{n})$，根据我们的目标方程，预测值为:


$\widehat {y}_{i}=w_{1}x^{\left( i\right) }_{1}+w_{2}x^{\left( i\right) }_{2}+w_{3}x^{\left( i\right) }_{3}+\ldots+w_{n}x^{\left( i\right) }_{n}+b$，真值为：$y_{i}$

<br/>

目标：使 $ \sum ^{m}_{i=1}\left( y_{i}-\widehat {y}_{i}\right) ^{2} $ 尽可能能小

$ w=\left( w_{1},w_{2},w_{3},\ldots ,w_{n}\right) $ ==>
$ W=\left( w,b\right)^{T}=\left( w_{1};w_{2};w_{3};\ldots ;w_{n};b\right) $  


$ x_{i}=\left( x^{\left( i\right) }_{1},x^{\left( i\right) }_{2},x^{\left( i\right) }_{3},\ldots ,x^{\left( i\right) }_{n}\right) $ ==>
$ X_{i}=\left( x_{i},1\right) $

`; 代表列向量，np向量默认就是列向量，而我们是把其实元素w和xi看成是行向量`

$ \widehat {y}_{i}=X_{i}\cdot W $

所以有：$ \sum ^{m}_{i=1}\left( y_{i}-\widehat {y}_{i}\right) ^{2} = \sum ^{m}_{i=1}\left( y_{i}-X_{i}\cdot W\right) ^{2}$

再扩展到m组数据：$ \sum ^{m}_{i=1}\left( y_{i}-\widehat {y}_{i}\right) ^{2} = \left( y-X\cdot W\right)^{T} \cdot \left( y-X\cdot W\right) $

然后对矩阵求导可得出当使上面的损失函数最小时的 W：$ W=\left( X^{T}X\right) ^{-1}X^{T}y $

<img src="../img/1.png" width="500" align="left"/>

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
boston = datasets.load_boston()
x=boston.data
y=boston.target

x=x[y<50]
y=y[y<50]

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=666)

### 实现一个线性回归器

In [3]:
class LinearRegression:
    def __init__(self):
        self.W_=None
        self.w_=None
        self.b_=None

    def fit_normal(self,X_train,y_train):
        X_b = np.hstack([X_train,np.ones((len(X_train),1))])
        W = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_train)

        self.W_ = W
        self.b_ = W[-1]
        self.w_ = W[:-1]
        return self

    def predict_normal(self,X_test):
        X_b = np.hstack([X_test,np.ones((len(X_test),1))])
        y_hat = X_b.dot(self.W_)
        return y_hat
    
    def __repr__(self):
        return "LinearRegression()"

In [4]:
reg = LinearRegression()
reg.fit_normal(X_train,y_train)
y_pred = reg.predict_normal(X_test)
reg.w_
reg.b_

LinearRegression()

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

34.11739972324508

In [5]:
from sklearn.metrics import r2_score

In [6]:
r2_score(y_test,y_pred)

0.8129794056212705

### scikit-learn中的线性回归

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
skreg = LinearRegression()

In [9]:
skreg.fit(X_train,y_train)
skreg.predict(X_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

array([18.08015868, 25.52447165, 12.98271397, 32.89477638, 24.17839745,
        2.66600125, 26.64297716, 32.23866352, 13.96590659, 24.0465123 ,
       14.92963   , 10.57419644, 30.28539981, 16.28302365, 23.67843428,
       25.63288299, 18.68105783, 24.01767076, 28.77234863, 26.9404495 ,
       12.87158142, 27.23259283, 26.07726096, 23.41270932, 20.80570812,
       31.96527196, 14.93177657, 20.94927605, 12.93149157, 29.8004438 ,
       35.29188752,  4.99369317, 13.10904465, 35.54982047, 16.00603155,
       21.53889058, 12.46701001, 29.12202629, 27.3433202 , 24.04852968,
       14.39961539, 23.61075774, 10.89223868, 22.38043687, 18.62604579,
       16.41773634, 24.43040765, 33.06929581, 19.19757395, 27.03634216,
       18.05693565, 14.90744724, 25.08683225, 16.09610653, 21.7469388 ,
       16.32259928, 24.25418684, 11.75290906, 27.91347808, 31.06610342,
       20.17028271, 24.99229322, 25.99180978, 12.11816691, 16.57739596,
       27.30354042, 22.26700274, 21.72088347, 31.5072238 , 14.09

In [10]:
# 截距b
skreg.intercept_

# 系数w
skreg.coef_

34.117399723229845

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [11]:
skreg.score(X_test,y_test)

0.8129794056212809

### 使用KNN解决回归问题

In [13]:
from sklearn.neighbors import KNeighborsRegressor

knn_reg = KNeighborsRegressor()
knn_reg.fit(X_train,y_train)
knn_reg.score(X_test,y_test)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

0.5865412198300899